name: ShellCheck
permissions: {}

on:
  push:
    paths:
      - ".github/workflows/shellcheck.yaml"
      - "**.sh"
  pull_request:
    paths:
      - ".github/workflows/shellcheck.yaml"
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
